# Generated by Django 5.1.1 on 2026-03-02 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_comment_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group', to='posts.group', verbose_name='группа'),
        ),
    ]
